AllCops:
  CacheRootDirectory: tmp/cache
  AllowSymlinksInCacheRootDirectory: true
  MaxFilesInCache: 8000
  TargetRubyVersion: 2.4

  Include:
    - Rakefile
    - config.ru
  Exclude:
    - .bundle/**/*
    - log/**/*
    - public/**/*
    - tmp/**/*
    - vendor/bundle/**/*
    - db/schema.rb
    - app/controllers/application_controller.rb
    - lib/curate/random.rb

Lint/AssignmentInCondition:
  Enabled: false

Lint/HandleExceptions:
  Exclude:
    - config/unicorn.rb

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 6

Metrics/PerceivedComplexity:
  Enabled: false

Performance/Count:
  Enabled: false

Performance/FixedSize:
  Enabled: false

Performance/TimesMap:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/BlockDelimiters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FileName:
  Exclude:
    - bin/**

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/IndentArray:
  EnforcedStyle: consistent

Style/IndentHash:
  EnforcedStyle: consistent

Style/Lambda:
  Enabled: false

Style/MultilineMethodCallBraceLayout:
  Enabled: false

Style/MultilineMethodCallIndentation:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/PredicateName:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

Style/SingleLineBlockParams:
  Enabled: false

Style/SpaceBeforeFirstArg:
  Enabled: false

Style/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/TrivialAccessors:
  AllowPredicates: True

Style/UnneededPercentQ:
  Enabled: false

Style/VariableNumber:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false
