default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: curate_development
  username: <%= ENV['LOCAL_USERNAME'] %>
  password:

test:
  <<: *default
  database: curate_test
  username: <%= ENV['LOCAL_USERNAME'] %>
  password:

production:
  <<: *default
  database: curate_production
  username: curate
  password: <%= ENV['CURATE_DATABASE_PASSWORD'] %>
